Repository Jocelyn-JE/AREA-51, pull requests merged in 2025-10, with the labels that each got.

#30 Login endpoint
  docs/swagger.yaml
  server/.eslintrc.js
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/routes/login.router.ts
  server/src/routes/register.router.ts
  server/src/utils/jwt.ts
  server/src/utils/request.validation.ts
Labels: back feature

#33 Google authentication in backend
  docs/swagger.yaml
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/routes/about.router.ts
  server/src/routes/auth.router.ts
  server/src/routes/login.router.ts
  server/src/routes/register.router.ts
  server/src/routes/swagger.router.ts
  server/src/utils/google.auth.ts
Labels: documentation, back feature

#40 Area creation endpoint
  server/init-mongo.js
  server/src/routes/about.router.ts
  server/src/routes/area.router.ts
  server/src/utils/db.ts
  server/src/utils/jwt.ts
Labels: back feature

#36 ✨ Front authentication, classic and google
  web_client/package-lock.json
  web_client/package.json
  web_client/src/components/Layout.tsx
  web_client/src/main.tsx
  web_client/src/pages/Explore.tsx
  web_client/src/pages/Login.tsx
  web_client/src/pages/Signup.tsx
Labels: front feature
